
--ASSIGNMENT - 6

--A-1: DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF ALL EMPLOYEES.

SELECT DEPT, COUNT(DEPT), SUM(SALARY) AS'TEAM SAL', AVG(SALARY) AS 'AVG SAL' FROM EMP
JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID
GROUP BY DEPT;

--A-2 : COUNT OF MANAGERS IN THE COMPANY.

SELECT COUNT(DESI) AS 'MANAGER COUNT'
FROM EMP_SAL
WHERE DESI LIKE '%MANAGER%';

--A-3: MAXIMUM & MINIMUM SALARY OF AN ASSOCIATE.

SELECT MAX(SALARY) AS 'MAX SAL' , MIN(SALARY) AS 'MIN SAL'
FROM EMP_SAL
WHERE DESI LIKE '%ASSOCIATE%';

--A-4: DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF DELHI EMPLOYEES.

SELECT DEPT, COUNT(DEPT) AS 'TEAM SIZE' , AVG (SALARY) AS 'AVG SAL' FROM EMP_SAL
JOIN EMP
ON EMP.EID = EMP_SAL.EID
WHERE CITY='DELHI'
GROUP BY DEPT;

--A -5 : GENERATE OFFICIAL EMAIL OF THE EMPLOYEE TAKING 1ST CHARATCET OF FIRST
--NAME , 1ST CHARATCER OF LAST NAME , LAST 3 DIGITS OF EID, FOLLED BY 'RCG.COM'.
--EMAIL SHOULD BE IN A UPPER CASE.

SELECT *  FROM EMP;

SELECT CONCAT(LEFT(NAME, 1), SUBSTRING(NAME,(CHARINDEX(' ',NAME)+1),1),RIGHT(EID,3),'RCG.COM') FROM EMP;

--A-6: NAME,CITY , PHNO & EMAIL OF THE EMPLOYEES WHOSE AGE >=40

SELECT NAME, CITY, PHONE ,EMAIL, DATEDIFF(YY,DOB,GETDATE()) AS 'AGE' FROM EMP
WHERE DATEDIFF(YY,DOB,GETDATE()) >= 40;

SELECT DATEDIFF(YY,DOB,GETDATE()) FROM EMP;
SELECT * FROM EMP_SAL;
--A-7 EID, NAME DOJ OF EMPLOYEES WHO HAVE COMPLETED 5 YEARS IN THE
--COMPANY

SELECT EMP.EID, NAME, DOJ , DATEDIFF(YY,DOJ,GETDATE()) AS 'YEARS IN COMP' FROM EMP
JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID
WHERE DATEDIFF(YY,DOJ,GETDATE())>=5;


--A-8: DETAILS OF THE MANAGERS HAVING BIRTHDAY IN THE CURRENT MONTH

SELECT * FROM EMP
WHERE MONTH(DOB)=MONTH(GETDATE());

--A-9 : EID, DEPT , DESI , SALARY OF THE EMPLOYEE WHO IS GETTING THE MAXIMUM
--SALARY

SELECT TOP 1 EMP.EID, DEPT, DESI, SALARY FROM EMP
JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID
ORDER BY SALARY DESC;

--A-IO : EID, NAME OF EMPLOYEE WHO HAS LONGEST NAME

SELECT TOP 1 EID, NAME, LEN(NAME) AS 'LEN'  FROM EMP
ORDER BY LEN  DESC;


--ASSIGNMENT - 7

--A-1: CREATE A FUNCTION CALC TO PERFORM THE SPECIFIED OPERATION ON THE
--GIVEN TWO NUMBERS .

DROP FUNCTION CALC;
CREATE FUNCTION CALC(@A AS INT, @B AS INT, @C AS CHAR(1))
RETURNS INT
AS
BEGIN 

	DECLARE @R AS INT

	IF @C = '+'
	SET @R = @A + @B;
	ELSE IF @C = '-'
	SET @R = @A - @B;	
	ELSE IF @C = '*'
	SET @R = @A * @B;	
	ELSE IF @C = '/'
	SET @R = @A / @B;	
	ELSE IF @C = '%'
	SET @R = @A % @B;	
	ELSE 
	SET @R = 0;	
	RETURN @R;

END;

SELECT  DBO.CALC(5,2,'-') AS 'RESULT';

--A-2: FUNCTION TO GENERATE THE EMAIL ID BY ACCEPTING NAME & EID. EMAIL
--SHOULD CONTAIN 1ST CHARACTER OF 1ST NAME , 1ST CHARACTER OF LAST NAME, LAST
--3 DIGITS OF EMP ID FOLLOWED BY @RCG.COM;

DROP FUNCTION GEN_EMAIL;
CREATE FUNCTION GEN_EMAIL(@A AS VARCHAR(50), @B AS CHAR(5))
RETURNS VARCHAR(50)
AS
BEGIN

		DECLARE @C AS VARCHAR(50)
		SET @C= CONCAT(LEFT(@A,1),SUBSTRING(@A,CHARINDEX(' ',@A)+1,1),RIGHT(@B,3),'@RCG.COM')

	RETURN @C

	END

SELECT DBO.GEN_EMAIL('ARUN KUMAR', 'E0901');


--A-3: FUNCTION TO RETURN EID, NAME, DESI, DEPT ,SALARY OF THE EMPLOYEES OF A
--SPECIFIED DEPARTMENT.

CREATE FUNCTION EMP_DET(@A AS CHAR(10))
RETURNS TABLE 
AS 
RETURN (
		SELECT EMP.EID, NAME, DESI, DEPT, SALARY FROM EMP
		JOIN EMP_SAL 
		ON EMP.EID = EMP_SAL.EID 
		WHERE DEPT = @A);

SELECT * FROM DBO.EMP_DET('IT');
--A-4: FUNCTION TO DISPLAY THE NAME , DEPT . DESI , CITY OF THE EMPLOYEES WHO
--HAVE THE BIRTHDAY IN THE CURRENT MONTH.

CREATE FUNCTION EMP_DET_BIR (@A AS INT)
RETURNS TABLE
AS
RETURN 
(SELECT NAME, DEPT, DESI, CITY FROM EMP
JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID
WHERE MONTH(DOB)=@A);

SELECT * FROM DBO.EMP_DET_BIR(10);
--A-5: FUNCTION TO DISPLAY THE NAME, DEPT & DOJ OF EMPLOYEES WHO HAVE
--COMPLETED 5 YEARS IN THE COMPANY.

CREATE FUNCTION FIVE_EMP(@A AS INT)
RETURNS TABLE
AS 
RETURN 
(SELECT NAME, DEPT ,DOJ FROM EMP
JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID
WHERE DATEDIFF(YY,DOJ,GETDATE()) = @A);

SELECT * FROM DBO.FIVE_EMP(5);


