--ASSIGNMENT -5
--IN THE EMP TABLE DISPLAY :
--1 ) EID NAME CITY DOJ DEPT DESI SALARY OF THE DELHI EMPLOYEES
--2 ) DETAILS OF ALL THE EMPLOYEES WHOSE SALARY DETAILS ARE NOT AVAILABLE.

SELECT EMP.EID, NAME, CITY, DOJ, DEPT, DESI, SALARY as 'BASIC'    
FROM EMP
INNER JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID and CITY= 'DELHI';

                  --OR--

SELECT EMP.EID, NAME, CITY, DOJ, DEPT, DESI, SALARY as 'BASIC'      -- By WHERE condition 
FROM EMP
INNER JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID 
WHERE CITY= 'DELHI';


SELECT * from emp
LEFT JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID
WHERE EMP_SAL.SALARY IS NULL ;


--IN THE INVENTORY STRUCTURE DISPLAY :
--1) PID, PDESC, CATEGORY, SNAME, SCITY
--2 ) DISPLAY OID , ODATE , CNAME, CADDRESS, CPHONE, PDESC, PRICE,OQTY, AMT

SELECT PID, PDESC, CATEGORY, SNAME, SCITY
FROM PRODUCT
LEFT JOIN SUPPLIER
ON PRODUCT.SID = SUPPLIER.SID;


SELECT OID, ODATE, CNAME, CADDRESS, PHONE, PDESC, PRICE, OQTY, PRICE * OQTY AS 'AMT' 
FROM ORDERS
JOIN CUST
ON ORDERS.CID = CUST.CID
JOIN PRODUCT
ON PRODUCT.PID = ORDERS.PID;
