--ASSIGNMENT - 3
--CREATE TWO TABLES EMP & EMP_SAL AS PER THE BELOW STRUCTURE:

--Field EID     Constraints
--EMPID         Primary Key
--NAME          NOT NULL
--ADDR          No employee from UTTAM NAGAR
--CITY          DEL, GGN, FBD, NOIDA
--PHNO          UNIQUE
--EMAIL         Should be on Gmail / Yahoo Domain
--DOB           <= '1-Jan-1990'

SELECT * FROM EMP_SAL

DROP TABLE EMP;       -- Drop a table
DROP TABLE EMP_SAL;

CREATE TABLE EMP
(EMPID CHAR(5) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
ADDR VARCHAR(50) CHECK (ADDR NOT LIKE '%UTTAM NAGAR%') NOT NULL,
CITY VARCHAR(20) DEFAULT 'DEL' CHECK (CITY IN('DEL', 'GGN', 'FBD', 'NOIDA')) NOT NULL, -- Default city is 'DEL'
PHONE VARCHAR(15) UNIQUE,
EMAIL VARCHAR(40) CHECK (EMAIL LIKE '%GAMIL%' OR EMAIL LIKE '%YAHOO%') NOT NULL,
DOB DATE CHECK (DOB <='01-JAN-1990') NOT NULL);

------------------------------------------------------------------------------------------------------------------------------------------------------

--EMP SAL Table
--Field EID   Constraints
--EMPID       Foreign Key
--DEPT        HR, MIS, OPS , IT ADMIN, TEMP
--DESI        ASSO, MGR, VP, DIR
--BASIC       >=20000
--DOJ         -
    --By default DEPT should be TEMP

CREATE TABLE EMP_SAL
(EMPID CHAR(5) FOREIGN KEY REFERENCES EMP(EMPID),
DEPT VARCHAR(10) DEFAULT 'TEMP' CHECK(DEPT IN ('HR','MIS','IT','ADMIN','TEMP')),
DESI VARCHAR(20) CHECK(DESI IN ('ASSO','MGR','VP','DIR')) NOT NULL,
BASIC FLOAT CHECK( BASIC >=20000) NOT NULL,
DOJ DATE NOT NULL);

SELECT * FROM EMP_SAL;

------------------------------------------------------------------------------------------------------------------------------------------------------

-- ASSIGNMENT -4

--In the EMP table display :
--CITY WISE COUNT OF EMPLOYEES ARRANGED IN DESCENDING ORDFER
--DETAILS OF THE EMPLOYEES WHO DOES NOT HAVE AN ACCOUNT ON YAHOO DOMAIN


SELECT COUNT(CITY) AS EMP_COUNT, CITY FROM EMP
GROUP BY CITY
ORDER BY CITY DESC;

SELECT * FROM EMP 
WHERE EMAIL NOT LIKE '%YAHOO%';


--From the Emp_SaI table display:
--DESIGNATION WISE TOTAL COST AND NUMBER OF MEMBERS ARRANGED IN DESCENDING ORDER OF THE TOTAL COST

SELECT DESI, COUNT(DESI) as MEMBERS ,SUM(SALARY) as TOTAL COST FROM EMP_SAL
GROUP By DESI
ORDER BY 'TOTAL COST' DESC;



--ASSIGNMENT - 6
--1 ) CREATE A VIEW EMP SAL DETAILS TO GET EID NAME DOJ DEPT DESI SALARY
--AS BASIC. ALSO CALCULATE HRA (15% OF BASIC), PF (9% OF BASIC),
--NET(BASIC+HRA+PF), GROSS(NET-PF).

CREATE VIEW EMP_SAL_DET
AS
SELECT NAME, DOJ, DEPT, DESI, SALARY AS 'BASIC', SALARY*0.15 AS 'HRA', SALARY*0.9 AS 'PF',
(SALARY + (SALARY*0.15) + (SALARY*0.9)) AS 'NET' , ((SALARY + (SALARY*0.15) + (SALARY*0.9))-(SALARY*0.9)) AS 'GROSS'
FROM EMP
JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID;

SELECT * FROM EMP_SAL_DET;


--2) CREATE A VIEW TO DISPLAY EID,NAME, DOJ, DESI, DEPT OF ALL THE
--MANAGERS JOINED IN 2019.

CREATE VIEW MAN_19
AS
SELECT EMP.EID, NAME, DOJ, DESI, DEPT
FROM EMP
JOIN EMP_SAL
ON EMP.EID = EMP_SAL.EID
WHERE DESI LIKE '%MANAGER%' AND YEAR(DOJ)= '2019';


--3) IN THE INVENTORY STRUCTURE GENERATE A VIEW BILL. IT SHOULD DISPLAY
--OID, ODATE, CNAME, ADDRESS, PHONE, PRICE, OQTY, AMOUNT

CREATE VIEW VIEW_BILL
AS
SELECT OID, ODATE, CNAME, CADDRESS, PHONE, PDESC, PRICE, OQTY, PRICE * OQTY AS 'AMT' 
FROM ORDERS
JOIN CUST
ON ORDERS.CID = CUST.CID
JOIN PRODUCT
ON PRODUCT.PID = ORDERS.PID;










